### ISSUE TITLE
如何生成小图

### ISSUE THREAD

**Issue by lijun20** [Jyouhou/CurvedSynthText#2]
![image](https://user-images.githubusercontent.com/6458704/65219374-035b5e00-daeb-11e9-9c31-406f29f0cf35.png)
你好，请问如何生成上图中的小图，因为我生成的是整个背景图片。

**Comment by lijun20** [comment]
你好，请问如何修改能支持中文？

**Comment by lijun20** [comment]
Hi, 你好，我能正常的生成英文图片，当我使用了中文字体和中文语料后，发现无法生成图片。
res = RV3.render_text(img, depth, seg, area, label, ninstance=args.instance_per_image, viz=False)  
返回的结果是空的，请问该如何解决？

**Comment by Jyouhou** [comment]
1. 你需要根据生成的标注裁剪
2. 你需要找一些中文字体

**Comment by lijun20** [comment]
> 1. 你需要根据生成的标注裁剪
> 2. 你需要找一些中文字体
你好，我找了几种中文字体，并添加在fontlist.txt中，newsgroup.txt中是中文语料，但是还是返回空的结果，无法找到问题在哪里？

**Comment by Jyouhou** [comment]
你可以试下把text_util.py这个文件单独拿出来，看看能否打印出文字。这样可能比较容易debug

**Comment by lijun20** [comment]
> 你可以试下把text_util.py这个文件单独拿出来，看看能否打印出文字。这样可能比较容易debug

好的，谢谢，我试试。我能控制文字的弯曲程度吗，需要设置哪个参数？

**Comment by lijun20** [comment]
![image](https://user-images.githubusercontent.com/6458704/65312137-7b498700-dbc4-11e9-88e9-f4006470e81c.png)
![image](https://user-images.githubusercontent.com/6458704/65312174-8d2b2a00-dbc4-11e9-931a-c3c2944938ad.png)
hi, 你好，如上图所示，我生成的中文为何是这样的？

**Comment by lijun20** [comment]
感谢

**Comment by Jyouhou** [comment]
请问问题解决了吗？弯曲程度请查看text_util.py里的render_curved函数，rho变量代表曲率，可以修改这个。

另外，你这个问题有可能是字体的问题。。。我也遇到过类似的。不过不知道pygame本身是否支持呢。

**Comment by lijun20** [comment]
> 请问问题解决了吗？弯曲程度请查看text_util.py里的render_curved函数，rho变量代表曲率，可以修改这个。
> 
> 另外，你这个问题有可能是字体的问题。。。我也遇到过类似的。不过不知道pygame本身是否支持呢。

你好，问题已经解决，是编码的问题
